#!/bin/sh

set -e

g++                                             \
    -I$HOME/ext/glfw/include                    \
    -I$HOME/ext/volk/                           \
    -I$HOME/ext/VulkanMemoryAllocator/include   \
    src/ttf.cpp                                 \
    src/mui.cpp -o mui                          \
    -L$HOME/ext/glfw/build/src -l:libglfw3.a

if test "$#" -ge 1 -a "$1" = "--run" ; then
    ./mui
fi
